### PR TITLE
Adding first released version of docs.

### PR DESCRIPTION
**Pull request by JWhitleyWork**
It turns out that you can't store raw HTML files as part of a GitHub Wiki. You also can't render HTML in GitHub wiki pages. In order to circumvent this, this PR adds the released HTML version to the GitHub repo and links to a preview of it from the Wiki. See https://github.com/astuff/pacmod_dbc/wiki for the implementation (the link to the HTML document will be updated once this PR is merged).

### CODE REVIEW

**Review by driscoll85 — DISMISSED** [review]

**Review by asaxsma — DISMISSED** [review]

**Comment by asaxsma** [comment]
Can the links find their way to the html via git tags?  Rather than circumventing version control by having an accumulation of unique file names, maybe we could have just one html file and use the url that includes the tags to create the link?  This would be more in the spirit of a version control system.  If not, than what you have is probably sufficient.

**Comment by JWhitleyWork** [comment]
@asaxsma - Actually, that's a good idea. Let me just make sure that I can use a tag in the URL for the preview and I'll get that implemented.

**Comment by JWhitleyWork** [comment]
@asaxsma - Yes, tags will work. However, I'll have to give this first one kind of an arbitrary tag (like 3.4.1.1) to get this first version up.

**Review by asaxsma — COMMENTED** [review]
Looks like the link on the wiki is broken.  I get this error when I press it "Error: Cannot load https://raw.githubusercontent.com/astuff/pacmod_dbc/maint/add_html_doc/doc/3.4.1.html: 404 Not Found"

**Comment by JWhitleyWork** [comment]
> Looks like the link on the wiki is broken. I get this error when I press it "Error: Cannot load https://raw.githubusercontent.com/astuff/pacmod_dbc/maint/add_html_doc/doc/3.4.1.html: 404 Not Found"

I was waiting for approval for the "arbitrary version" I mentioned. I've updated it and it will work now.

**Review by asaxsma — APPROVED** [review]
Oh, okay, thought it was all one working system.  I assume we'll still automatically generate links on the wiki each named according to the release version number, but instead of linking to a unique file, they will link through a tag to a generic file?

**Comment by JWhitleyWork** [comment]
@asaxsma - I haven't implemented the "auto-generate the file" portion yet. This is a first, manual run. I'm still trying to figure out the order of operations.

**Review by driscoll85 — APPROVED** [review]

**Comment by srustanAStuff** [comment]
I still see the 404. Is that intended?

**Comment by JWhitleyWork** [comment]
> I still see the 404. Is that intended?

Have you gone to the wiki page and hit refresh? The link in the menu on the right works correctly for me.

@srustanAStuff - Don't use the link that @asaxsma posted. Go to the wiki tab and click on the link.

**Comment by JWhitleyWork** [comment]
@srustanAStuff - Please re-try and review.

**Review by srustanAStuff — APPROVED** [review]

**Pull request merged**
