### PR TITLE
Change 009

### PR DESCRIPTION
**Pull request by mlemm99**

### CODE REVIEW

**Review by JWhitleyWork — DISMISSED** [review]

**Comment by JWhitleyWork** [comment]
Closes #39. Closes #38. Closes #37. Closes #35. Closes #34.

**Comment by asaxsma** [comment]
Found some issues to resolve:
1. Looks like spray system flag wasn't added to the component reports.
2. Need  0 "NO_FAULT" 1 "FAULT" for ESTOP_FAULT like the other faults in the component report.
3. Sprayer command needs to be assigned to the "CUSTOMER_ECU".
4. Wiper report value definitions for intermittent need to be updated.

**Comment by asaxsma** [comment]
Sorry, hit wrong button.

**Review by JWhitleyWork — APPROVED** [review]

**Review by driscoll85 — APPROVED** [review]

**Review by asaxsma — APPROVED** [review]

**Comment by asaxsma** [comment]
This issue also addresses #26 and #30.

**Pull request merged**
